### PR TITLE
Diagnostics are poor when misconfiguration leads to operation-specific configuration being null

### PR DESCRIPTION
**Pull request by nosan**
see more [here](https://github.com/spring-projects/spring-boot/issues/15976)

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. As mentioned in [my comment](
https://github.com/spring-projects/spring-boot/issues/15976#issuecomment-464709580) on the Spring Boot issue, the problem isn't specific to `WebTestClient`. If a change is to be made here, it should be done for MockMvc and REST Assured as well. Would you like to do that as part of this proposal?

**Comment by nosan** [comment]
@wilkinsona sure, I had some thoughts about this.

**Comment by nosan** [comment]
@wilkinsona I added `Assert.state(configuration != null)` for `RestAssured`, `MockMvc` and `WebTestClient`, but I have a problem with a build:
```

> Task :restNotesGrailsGradle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':restNotesGrailsGradle'.
> Process 'command './gradlew'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
Also, I had tried to build a `master` branch, and It was not built as well. 

Have I missed something?

**Comment by wilkinsona** [comment]
Thanks for your patience, @nosan, and for your first contribution to Spring REST Docs. The proposed changes have now been merged into master.

**Comment by nosan** [comment]
Everything is ok :) Thanks

**Pull request closed without merging**
