### PR TITLE
Fix asciidoctor-maven-plugin's phase

### PR DESCRIPTION
**Pull request by making**
The document (6) explains `prepare-package` should be used, but the example is `package`.

Actually, I had a trouble copying and pasting according to this doc.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Sorry that you found this confusing. The need to use `prepare-package` if you want to include the documentation in the jar file is mentioned in the call out referenced by (6):

> (6) If you want to package the documentation in your project’s jar you should use the `prepare-package` phase.

It's also mentioned again in the [Packaging the documentation](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-build-configuration-maven-packaging) section:

> First, configure the Asciidoctor plugin so that it runs in the prepare-package phase, as described above

If you have suggestions for how to make this clearer, I'd definitely like to hear them. However, I can't merge this change in its current form it'll mean that the sections mentioned above (among others) no longer make sense.

**Comment by making** [comment]
Thank you for your comment.
I found I had misunderstood.

Updated PR to explain the phase explicitly.
How do you think?

**Comment by wilkinsona** [comment]
Having thought about this some more, I think it might be best to update the documentation to always use `prepare-package` for the phase. It'll be a lot simpler as it'll mean one set of instructions that'll work for those who want to embed the documentation in the jar and those that don't.

**Comment by wilkinsona** [comment]
Thanks for the PR. As discussed above, I've decided to address the problem by recommending that the Asciidoctor plugin is always bound to the `prepare-package` phase. See #218 for that change.

**Pull request closed without merging**
