### PR TITLE
Dynamic ToC and PDF output

### PR DESCRIPTION
**Pull request by Buzzardo**
I updated the document-production parts of the build files to pick up the dynamic ToC (tocbot) that we use across the portfolio. I also added PDF output (again, in keeping with the rest of the portfolio). In doing so, I updated various versions and other settings.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, Jay. I guess this supersedes #577? That has yet to be merged as work on 2.1 still hasn't begun.

**Comment by Buzzardo** [comment]
I had forgotten about that one. I figured I had missed spring-restdocs in my modernization push some time back.

Anyway, this one can supercede that one. It doesn't have conflicts, and I'm sure I know more now than I did then.

I'll go close https://github.com/spring-projects/spring-restdocs/pull/577

**Comment by Buzzardo** [comment]
Is there anything holding up merging this PR or can we go ahead?

**Comment by wilkinsona** [comment]
It can't be merged until the 2.0.x branch has been created and master switches to 2.1.

**Comment by wilkinsona** [comment]
Superseded by #773.

**Pull request closed without merging**
