### PR TITLE
Consider request parameters in CurlDocumentation writer

### PR DESCRIPTION
**Pull request by yleguern**
A proposal to resolve the `"Consider request parameters when determining a GET request's query string"` issue

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks. Have you [signed the CLA](https://github.com/spring-projects/spring-restdocs/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement)?

**Comment by yleguern** [comment]
I just did.

**Comment by wilkinsona** [comment]
Thanks for the PR. I've merged it with one notable change: I removed the logic for handling request parameters for POST requests as I'm not sure that it's necessary for a RESTful services and #26 was specifically looking to address GET requests.

**Comment by yleguern** [comment]
Thanks for the merge.
But why did you remove the logic for `POST` requests ?
I think it's especially interesting in case of `POST` requests because I can't see no workaround to document `POST` requests with parameters : 

```java
this.mvc.perform(MockMvcRequestBuilders
  .post(Constants.URL_GET_TOKEN)
  .param(PARAM_USERNAME, "user")
  .param(PARAM_PASSWORD, "userpwd"))
  .andExpect(status().isOk())
  .andDo(document("retrieveTokenViaPost"))
```

**Comment by wilkinsona** [comment]
I tried to explain my reasoning above. The primary reason was because issue #26, which this PR was addressing, was specifically interested in GET requests. If there's a valid use case for POST requests then I'd prefer to tackle it in a separate issue.

**Pull request closed without merging**
