### PR TITLE
Add context path as modifiable URI part for RestAssured

### PR DESCRIPTION
**Pull request by wjans**
Also expose context path on the URI modifying preprocessor for RestAssured.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. What's the problem that it is trying to address? I had imagined that a service could be tested locally using whatever context path is required and the host, scheme, and port can then be modified to reflect the real service.

**Comment by wjans** [comment]
We are using Zuul as a gateway for our microservices. So we write our tests locally and we would like to modify the URI to the URI as it is exposed on the gateway, i.e. including the context path as it is configured in our Zuul routes.

**Comment by wilkinsona** [comment]
Rather than modifying the URI to have a different context path, why not just run your micro service locally with that context path when you're generating its documentation?

**Comment by wjans** [comment]
You mean by overriding it in the test configuration to 'fake' the path being used by the gateway?  I thought it would be nicer to have it explicitly defined.  It would also allow me to specify the zuul specific configuration all together in the same place (scheme/host/port/path).

**Comment by wilkinsona** [comment]
> You mean by overriding it in the test configuration to 'fake' the path being used by the gateway?

Yes. For example, if it were a Spring Boot app, you'd just set `server.context-path=/foo` when running the tests that generate the documentation.

> It would also allow me to specify the zuul specific configuration all together in the same place (scheme/host/port/path).

I can see the benefit to that, but, assuming that you can "fake" the context path, I'm not yet convinced that the added complexity in REST Docs is worth it.

**Comment by wjans** [comment]
Ok, I will rewrite my tests like you suggest, and maybe create some reusable factory methods reading the zuul configuration, which will also allow me to have it in one place.

**Pull request closed without merging**
