### PR TITLE
add printing query params in curl documentation

### PR DESCRIPTION
**Pull request by andrewmerc21**
Commit adds printing of request parameters in request documentation.
for example 
$ curl http://localhost:8080/settlement?id=123 -i -H "Accept: application/json"

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR.

This project's going to move over to the [Spring Projects organisation](https://github.com/spring-projects). Once it's there I'll be able to accept PRs from anyone who's signed the contributor licence agreement. I'll comment again with more details after the move.

**Comment by andrewmerc21** [comment]
okay, sure

**Comment by wilkinsona** [comment]
The project's moved over now. Can you please [sign the CLA](https://github.com/spring-projects/spring-restdocs/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement)?

**Comment by andrewmerc21** [comment]
Hi, can you please specify which project should I choose in the CLA form? There is no option for restdocs.

**Comment by wilkinsona** [comment]
Apologies. I'd forgotten about the project drop-down on the form. I'll let you know once it's been updated.

**Comment by wilkinsona** [comment]
The form's been updated and Spring REST Docs is now list in the projects drop-down. Hopefully that's the final piece in the puzzle. Sorry it's been a little convoluted, thankfully you only need to sign once.

**Comment by andrewmerc21** [comment]
Okay thanks. I've signed it. My confirmation number is 108220150217110755

**Comment by wilkinsona** [comment]
I've made a few comments in the commit (see above). Would you like to update the PR?

**Comment by andrewmerc21** [comment]
Yeah sure. I'll update it soon.

**Comment by andrewmerc21** [comment]
I've created new pull request, for this feature.

**Pull request closed without merging**
