### PR TITLE
Dont enforce varies type on field which might have null in some of th…

### LINKED ISSUE #398: Field beneath an array that is sometimes null cannot have a type other than varies
In a response containing an array, certain fields could be sometimes null and sometimes not. Currently JsonFieldTypeResolver marks them as Varies. This forces me to document the fields as Varies. Which IMO doesnt add any value to the docs. This leads to following error.

`org.springframework.restdocs.payload.FieldTypesDoNotMatchException: The documented type of the field '[].obj' is Array but the actual type is Varies`

Would it wise to make an exception for null?

here is an example patch

```diff
diff --git a/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java b/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java
index 25c373c..e618a4b 100644
--- a/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java
+++ b/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java
@@ -35,10 +35,10 @@ class JsonFieldTypeResolver {
                        JsonFieldType commonType = null;
                        for (Object item : (Collection<?>) field) {
                                JsonFieldType fieldType = determineFieldType(item);
-                               if (commonType == null) {
+                               if (commonType == null && fieldType !== JsonFieldType.NULL) {
                                        commonType = fieldType;
                                }
-                               else if (fieldType != commonType) {
+                               else if (fieldType != commonType && fieldType !== JsonFieldType.NULL) {
                                        return JsonFieldType.VARIES;
                                }
                        }
```

I could use `@JsonInclude(JsonInclude.Include.NON_NULL)` to prevent null fields in REST response but I'd like to avoid that and use null and have consistent REST response with all fields.

### PR DESCRIPTION
**Pull request by nakulcg**
…e items in an array in a REST response  fixes #398

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nakulcg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-restdocs&pullRequestId=399)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-restdocs&pullRequestId=399) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@nakulcg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-restdocs&pullRequestId=399)!

**Comment by wilkinsona** [comment]
Thanks for the PR. Did you intend to undo the commit that proposed a fix for the problem?

**Comment by nakulcg** [comment]
Yes. Because I think it might introduce other problems. Because it then renders the JsonFieldType.NULL useless.

**Comment by wilkinsona** [comment]
Got you, thanks. Yeah, your test actually reveals another problem which is that it should fail because you haven't marked `assets[].name` as optional yet it isn't always there. I've opened https://github.com/spring-projects/spring-restdocs/issues/402 for that.

**Comment by wilkinsona** [comment]
Thanks for the PR, @nakulcg

**Pull request closed without merging**
