### PR TITLE
Support text/xml & application/rss+xml media types

### PR DESCRIPTION
**Pull request by eddumelendez**
This commit adds support to process two more content types.

See gh-393

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez. Rather than hard-coding some additional media types, I think it would be better to check for compatibility against `*/*+xml`. That would mean that standard media types like `application/xml`, `text/xml`, and `application/rss+xml` are all supported, as well as custom media types like `application/vnd.com.example+xml`

Would you like to update your PR to do that?

**Comment by eddumelendez** [comment]
@wilkinsona Thanks for your feedback. Glad to update the PR and now I'm doing the following

```java
private boolean isCompatibleWithXml(MediaType contentType) {
    MediaType xmlMediaType = new MediaType("*", "*+xml");
    return xmlMediaType.isCompatibleWith(contentType);
}
```

but since the type is "*" even "application/json" is valid for xml. Pretty sure I misunderstood something in the process to do this. Could you provide any hint? Thanks in advance.

**Comment by wilkinsona** [comment]
Nope, you haven't misunderstood. Using a check against `*/*+xml` was wishful thinking on my part. We could check for `application/xml`, `text/xml`, `application/*+xml` and `text/*+xml` but that would still miss custom XML media types as well as things like `image/svg+xml`. 

I now think that the most robust approach would be to treat the content as JSON by default. If that throws an exception then try XML. If that throws an exception then give up.

**Comment by wilkinsona** [comment]
Thank you for your efforts here, @eddumelendez. There's more time pressure than usual here as 1.2.1.RELEASE is needed for Spring Boot 2.0.0.M1 so I've fixed #393 in https://github.com/spring-projects/spring-restdocs/commit/113976f2d9eb076e0f38e343629f23bea95155b9. Thanks anyway.

**Pull request closed without merging**
