### PR TITLE
Query parameters with multiple values are not handled correctly when using REST Assured

### PR DESCRIPTION
**Pull request by pvardanega**
Fixes gh-476

### CODE REVIEW

**Comment by pvardanega** [comment]
Should I also apply the changes on branch 1.2.x?

**Comment by wilkinsona** [comment]
Thanks, but no need to do that. I can cherry-pick it onto 1.2.x and then merge forwards to master.

**Comment by pvardanega** [comment]
Hi @wilkinsona 
Is there anything preventing this pull request to be merged? Feel free to give me some feedbacks so that I can't improve it.
Regards

**Comment by wilkinsona** [comment]
Nothing other than a lack of time on my side. I hope to get to it once Boot 2.0 RC2 has been released early next week.

**Comment by pvardanega** [comment]
Ahah ok, no problem. Thank you for your work!

**Comment by wilkinsona** [comment]
Thanks very much for making your first contribution to Spring REST Docs, @pvardanega. Your changes are now in both 1.2.x and master.

**Pull request closed without merging**
